name: first workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: windows-latest

    steps:
      - name: print a welcome message
        run: echo "Welcome to our first GitHub Actions workflow"  # run on Windows
      - name: checkout repository
        uses:  actions/checkout@v5.0.0
      - name: list repository files
        run: Get-ChildItem -Force
        
      
